// examples/nextjs/src/components/Header.tsx
'use client';

import { ConnectButton } from '@btc-connect/react';

interface HeaderProps {
  theme?: 'light' | 'dark';
}

export function Header({ theme = 'light' }: HeaderProps) {
  return (
    <header style={{
      backgroundColor: theme === 'light' ? '#ffffff' : '#1a1a1a',
      borderBottom: `2px solid ${theme === 'light' ? '#f7931a' : '#f7931a'}`,
      padding: '16px 0',
      boxShadow: theme === 'light'
        ? '0 2px 8px rgba(0,0,0,0.1)'
        : '0 2px 8px rgba(0,0,0,0.3)',
      position: 'sticky' as const,
      top: 0,
      zIndex: 100,
      backdropFilter: 'blur(8px)'
    }}>
      <div style={{
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '0 20px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center'
      }}>
        {/* Logo 和标题 */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px'
        }}>
          {/* Bitcoin Logo */}
          <div style={{
            width: '40px',
            height: '40px',
            backgroundColor: '#f7931a',
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            boxShadow: '0 2px 8px rgba(247, 147, 26, 0.3)'
          }}>
            <svg
              width="24"
              height="24"
              fill="white"
              viewBox="0 0 24 24"
              style={{ display: 'block' }}
            >
              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.56c-.21-.81-.84-1.29-1.84-1.29H10v8h2v-3h2.5c1 0 1.63-.48 1.84-1.29.2-.76-.01-1.58-.56-2.09.55-.51.76-1.33.56-2.09z"/>
            </svg>
          </div>

          {/* 标题文字 */}
          <div>
            <h1 style={{
              margin: 0,
              fontSize: '24px',
              fontWeight: 'bold',
              color: theme === 'light' ? '#212529' : '#ffffff',
              lineHeight: '1.2'
            }}>
              BTC Connect
            </h1>
            <p style={{
              margin: 0,
              fontSize: '14px',
              color: theme === 'light' ? '#6c757d' : '#adb5bd',
              marginTop: '2px'
            }}>
              Next.js 测试套件
            </p>
          </div>
        </div>

        {/* 右侧钱包连接按钮 */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: '16px'
        }}>
          <div style={{
            fontSize: '14px',
            color: theme === 'light' ? '#6c757d' : '#adb5bd'
          }}>
            钱包连接
          </div>
          <ConnectButton
            size="md"
            variant="select"
            label="连接钱包"
          />
        </div>
      </div>
    </header>
  );
}

// examples/nuxt-example/components/Header.vue
<template>
  <header class="sticky top-0 z-50 backdrop-blur-md border-b-2 border-orange-500 shadow-lg">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center py-4">
        <!-- Logo 和标题 -->
        <div class="flex items-center space-x-3">
          <!-- Bitcoin Logo -->
          <div class="w-10 h-10 bg-orange-500 rounded-full flex items-center justify-center shadow-lg">
            <svg class="w-6 h-6 text-white" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.56c-.21-.81-.84-1.29-1.84-1.29H10v8h2v-3h2.5c1 0 1.63-.48 1.84-1.29.2-.76-.01-1.58-.56-2.09.55-.51.76-1.33.56-2.09z"/>
            </svg>
          </div>

          <!-- 标题文字 -->
          <div>
            <h1 class="text-2xl font-bold text-gray-900 dark:text-white leading-tight">
              BTC Connect
            </h1>
            <p class="text-sm text-gray-600 dark:text-gray-400 mt-0.5">
              Nuxt.js 测试套件
            </p>
          </div>
        </div>

        <!-- 右侧钱包连接按钮 -->
        <div class="flex items-center space-x-4">
          <ClientOnly>
            <ConnectButton
              size="md"
              variant="select"
              label="连接钱包"
            />
          </ClientOnly>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
// 组件配置
defineProps<{
  theme?: 'light' | 'dark'
}>();

// 页面元数据
useHead({
  title: 'BTC Connect - Nuxt 3 完整测试套件',
  meta: [
    { name: 'description', content: 'Bitcoin wallet connection complete test suite using Nuxt 3' }
  ]
})
</script>

<style scoped>
/* 自定义样式 */
header {
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(12px);
}

.dark header {
  background: rgba(26, 26, 26, 0.95);
}

/* 响应式调整 */
@media (max-width: 640px) {
  .flex.justify-between {
    flex-direction: column;
    gap: 1rem;
  }

  .flex.items-center.space-x-4 {
    width: 100%;
    justify-content: space-between;
  }

  .flex.items-center.space-x-3 {
    width: 100%;
  }

  .text-sm {
    display: none;
  }
}
</style>
